clean up

diff --git a/powerdown-utils b/powerdown-utils
--- a/powerdown-utils
+++ b/powerdown-utils
@@ -3,28 +3,24 @@
 # turn on kernel options
 opt() {
   [[ -f $1 ]] || return
-  echo $2 | tee $1 &>/dev/null
-  [[ $? != 0 ]] && echo "[powerdown] cannot enable option $1"
+  echo $2 | tee $1 &>/dev/null || echo "[powerdown] cannot enable option $1"
 }
 
 # unload kernel module
 unload() {
   modinfo $1 &>/dev/null || return
   [[ $(lsmod | grep $1) == "" ]] && return
-  rmmod -w $1 &>/dev/null
-  [[ $? != 0 ]] && echo "[powerdown] cannot unload module $1"
+  rmmod -w $1 &>/dev/null || echo "[powerdown] cannot unload module $1"
 }
 
 # load kernel module
 load() {
   modinfo $1 &>/dev/null || return
   [[ $(lsmod | grep $1) == "" ]] || return
-  modprobe $1 &>/dev/null
-  [[ $? != 0 ]] && echo "[powerdown] cannot load module $1"
+  modprobe $1 &>/dev/null || echo "[powerdown] cannot load module $1"
 }
 
 # command
 run() {
-  $@ &> /dev/null
-  [[ $? != 0 ]] && echo "[powerdown] cannot run $@"
+  $@ &> /dev/null || echo "[powerdown] cannot run $@"
 }
