more precise lsmod

diff --git a/powerdown-utils b/powerdown-utils
--- a/powerdown-utils
+++ b/powerdown-utils
@@ -3,20 +3,20 @@
 # turn on kernel options
 opt() {
   [[ -f $1 ]] || return
-  echo $2 | tee $1 &>/dev/null || echo "[powerdown] cannot enable option $1"
+  echo $2 | tee $1 &>/dev/null || echo "[powerdown] cannot write $2 to $1"
 }
 
 # unload kernel module
 unload() {
   modinfo $1 &>/dev/null || return
-  [[ $(lsmod | grep $1) == "" ]] && return
+  [[ $(lsmod | cut -f 1 -d " " | grep "^$1$") == "" ]] && return
   rmmod -w $1 &>/dev/null || echo "[powerdown] cannot unload module $1"
 }
 
 # load kernel module
 load() {
   modinfo $1 &>/dev/null || return
-  [[ $(lsmod | grep $1) == "" ]] || return
+  [[ $(lsmod | cut -f 1 -d " " | grep "^$1$") == "" ]] || return
   modprobe $1 &>/dev/null || echo "[powerdown] cannot load module $1"
 }
 
