quote

diff --git a/powerdown-functions b/powerdown-functions
--- a/powerdown-functions
+++ b/powerdown-functions
@@ -3,53 +3,53 @@
 
 # turn on kernel options
 opt() {
-  [[ -f $1 ]] || return
-  echo $2 | tee $1 &>/dev/null || echo "[powerdown] cannot write $2 to $1"
+  [[ -f "$1" ]] || return
+  echo "$2" | tee "$1" &>/dev/null || echo "[powerdown] cannot write $2 to $1"
 }
 
 # unload kernel module
 unload_mod() {
-  has_mod $1 || return
-  mod_loaded $1 || return
-  modprobe -r $1 &>/dev/null || echo "[powerdown] cannot unload module $1"
+  has_mod "$1" || return
+  mod_loaded "$1" || return
+  modprobe -r "$1" &>/dev/null || echo "[powerdown] cannot unload module $1"
 }
 
 # load kernel module
 load_mod() {
-  has_mod $1 || return
-  mod_loaded $1 && return
-  modprobe $1 &>/dev/null || echo "[powerdown] cannot load module $1"
+  has_mod "$1" || return
+  mod_loaded "$1" && return
+  modprobe "$1" &>/dev/null || echo "[powerdown] cannot load module $1"
 }
 
 # module exists
 has_mod() {
-  modinfo $1 &>/dev/null
+  modinfo "$1" &>/dev/null
   return $?
 }
 
 # module loaded
 mod_loaded() {
-  [[ $(lsmod | cut -f 1 -d " " | grep "^$1$") != "" ]] && return 0 || return 1
+  [[ "$(lsmod | cut -f 1 -d " " | grep "^$1$")" != "" ]] && return 0 || return 1
 }
 
 # command
 run() {
-  $@ &> /dev/null || echo "[powerdown] cannot run $@"
+  "$@" &> /dev/null || echo "[powerdown] cannot run $@"
 }
 
 # get current power usage
 display_power() {
-  if [[ $(find /sys/class/power_supply -name BAT*) == "" ]]; then
+  if [[ "$(find /sys/class/power_supply -name BAT*)" == "" ]]; then
     echo "[powerdown] no battery"
     return
   fi
   for bat in /sys/class/power_supply/BAT*; do
-    if [[ -f $bat/power_now ]]; then
-      watt=$(echo "scale=3;$(cat $bat/power_now)/1000000" | bc)
+    if [[ -f "$bat/power_now" ]]; then
+      watt="$(echo "scale=3;$(cat "$bat"/power_now)/1000000" | bc)"
     else
-      watt=$(echo "scale=3;$(cat $bat/current_now)/1000000" | bc)
+      watt="$(echo "scale=3;$(cat "$bat"/current_now)/1000000" | bc)"
     fi
-    echo "[powerdown] $(basename $bat) using $watt watts"
+    echo "[powerdown] $(basename "$bat") using $watt watts"
   done
   if [[ -f /usr/bin/acpi ]]; then
     acpi
@@ -58,23 +58,23 @@ display_power() {
 
 # get readahead
 display_readahead() {
-  echo " -> $1 readahead: $(blockdev --getra $1)"
+  echo " -> $1 readahead: $(blockdev --getra "$1")"
 }
 
 # dump kernel option content
 dump () {
-  [[ -w $1 && -r $1 ]] || return
+  [[ -w "$1" && -r "$1" ]] || return
   echo " -> $1: $(cat $1)"
 }
 
 display_module() {
-  has_mod $1 || return
+  has_mod "$1" || return
   echo -n " -> $1 "
-  mod_loaded $1 && echo "loaded" || echo "not loaded"
+  mod_loaded "$1" && echo "loaded" || echo "not loaded"
 }
 
 display_wireless() {
-  echo " -> $1 $(iw dev $1 get power_save)"
+  echo " -> $1 $(iw dev "$1" get power_save)"
 }
 
 hibernate_offset() {
@@ -86,7 +86,7 @@ root_part() {
 }
 
 has_swap_part () {
-    [[ $(grep swap /etc/fstab) != "" ]]
+    [[ "$(grep swap /etc/fstab)" != "" ]]
 }
 
 can_suspend_to_disk () {
@@ -108,10 +108,10 @@ resume_boot_option() {
 # lock the file until the script finishes
 lock() {
     LOCK=/tmp/powerdown.lock
-    if [[ -f $LOCK ]]; then
+    if [[ -f "$LOCK" ]]; then
         echo "Working... $LOCK"
         exit
     fi
-    : > $LOCK
+    : > "$LOCK"
     trap "rm -f $LOCK; exit" EXIT
 }
