reindent

diff --git a/powerdown-functions b/powerdown-functions
--- a/powerdown-functions
+++ b/powerdown-functions
@@ -3,22 +3,22 @@
 
 # turn on kernel options
 opt() {
-  [[ -f "$1" ]] || return
-  echo "$2" | tee "$1" &>/dev/null || echo "[powerdown] cannot write $2 to $1"
+    [[ -f "$1" ]] || return
+    echo "$2" | tee "$1" &>/dev/null || echo "[powerdown] cannot write $2 to $1"
 }
 
 # unload kernel module
 unload_mod() {
-  has_mod "$1" || return
-  mod_loaded "$1" || return
-  modprobe -r "$1" &>/dev/null || echo "[powerdown] cannot unload module $1"
+    has_mod "$1" || return
+    mod_loaded "$1" || return
+    modprobe -r "$1" &>/dev/null || echo "[powerdown] cannot unload module $1"
 }
 
 # load kernel module
 load_mod() {
-  has_mod "$1" || return
-  mod_loaded "$1" && return
-  modprobe "$1" &>/dev/null || echo "[powerdown] cannot load module $1"
+    has_mod "$1" || return
+    mod_loaded "$1" && return
+    modprobe "$1" &>/dev/null || echo "[powerdown] cannot load module $1"
 }
 
 # module exists
@@ -39,24 +39,24 @@ brightness_scale() {
 
 # command
 run() {
-  "$@" &> /dev/null || echo "[powerdown] cannot run $@"
+    "$@" &> /dev/null || echo "[powerdown] cannot run $@"
 }
 
 # get current power usage
 display_power() {
-  if [[ "$(find /sys/class/power_supply -name BAT*)" == "" ]]; then
-    echo "[powerdown] no battery"
-    return
-  fi
-  for bat in /sys/class/power_supply/BAT*; do
-    local watt
-    if [[ -f "$bat/power_now" ]]; then
-      watt="$(echo "scale=3; $(cat "$bat"/power_now) / 1000000" | bc)"
-    else
-      watt="$(echo "scale=3; $(cat "$bat"/current_now) / 1000000" | bc)"
+    if [[ "$(find /sys/class/power_supply -name BAT*)" == "" ]]; then
+        echo "[powerdown] no battery"
+        return
     fi
-    echo "[powerdown] $(basename "$bat") using $watt watts"
-  done
+    for bat in /sys/class/power_supply/BAT*; do
+        local watt
+        if [[ -f "$bat/power_now" ]]; then
+            watt="$(echo "scale=3; $(cat "$bat"/power_now) / 1000000" | bc)"
+        else
+            watt="$(echo "scale=3; $(cat "$bat"/current_now) / 1000000" | bc)"
+        fi
+        echo "[powerdown] $(basename "$bat") using $watt watts"
+    done
 }
 
 # get readahead
@@ -129,7 +129,7 @@ usb_powersave() {
                 break
             fi
         done
-        
+
         if $run; then
             opt $usbdev/power/control auto
         else
