clean up

diff --git a/powerdown-functions b/powerdown-functions
--- a/powerdown-functions
+++ b/powerdown-functions
@@ -6,21 +6,19 @@ shopt -s nullglob extglob
 # turn on kernel options
 opt() {
     [[ -f "$1" ]] || return
-    tee "$1" <<<"$2" &>/dev/null || echo "[powerdown] cannot write $2 to $1"
+    [[ -w "$1" ]] && echo "$2" > "$1" || echo "[powerdown] cannot write $2 to $1"
 }
 
 # unload kernel module
 unload_mod() {
     has_mod "$1" || return
-    mod_loaded "$1" || return
-    modprobe -r "$1" &>/dev/null || echo "[powerdown] cannot unload module $1"
+    modprobe -r "$1" || echo "[powerdown] cannot unload module $1"
 }
 
 # load kernel module
 load_mod() {
     has_mod "$1" || return
-    mod_loaded "$1" && return
-    modprobe "$1" &>/dev/null || echo "[powerdown] cannot load module $1"
+    modprobe "$1" || echo "[powerdown] cannot load module $1"
 }
 
 # module exists
@@ -37,8 +35,7 @@ mod_loaded() {
 # $1 = max file
 # $2 = value
 num_scale() {
-    local scale="$(bc <<< "$(< "$1") / 5")"
-    echo "$(( $scale * $2 ))"
+    bc <<< "$(< "$1") / 5 * $2"
 }
 
 # command
@@ -79,7 +76,7 @@ display_readahead() {
 
 # dump kernel option content
 dump () {
-    [[ -w "$1" && -r "$1" ]] || return
+    [[ -r "$1" ]] || return
     echo " -> $1: $(< "$1")"
 }
 
